name: Marlin Firmware Build Pipeline

on: [push]

env:
  board: 'STM32F103RET6_creality'
  marlinBranch: 'bugfix-2.0.x'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install Dependencies
      run: |
        pip3 install -U https://github.com/platformio/platformio-core/archive/develop.zip
        platformio update
        pip3 install PyYaml
    
    - name: Checkout Marlin repo
      uses: actions/checkout@v2
      with:
        repository: MarlinFirmware/Marlin
        path: Marlin
        ref: ${{ env.marlinBranch }}
    
    - name: Copy Configurations
      run: |
        cp -rf configurations/${{ env.board }}/Configuration.h Marlin/Marlin/
        cp -rf configurations/${{ env.board }}/Configuration_adv.h Marlin/Marlin/

    - name: Run PlatformIO
      run: |
        cd Marlin/
        pio run -e ${{ env.board }}
